version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev.django
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     ./.env.db

volumes:
  postgres_data: