# pull official base image
FROM python:3.9-slim-bullseye

# set work directory
WORKDIR /opt/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
# COPY ./entrypoint.sh .
# RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
# RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY assets assets/
COPY bundles bundles/
COPY foodcartapp foodcartapp/
COPY geodata geodata/
COPY media media/
COPY restaurateur restaurateur/
COPY star_burger star_burger/
COPY static static/
COPY templates templates/
COPY manage.py .

# run entrypoint.sh
# ENTRYPOINT ["/usr/src/app/entrypoint.sh"]