# pull official base image
FROM node:16

# set work directory
WORKDIR /opt/app/

COPY package*.json ./

RUN npm ci --dev

CMD ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
