version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev.django
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     ./.env.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: