#!/bin/bash

set -e

source .env

cd /opt/star-burger

git  pull

/opt/star-burger/venv/bin/pip install -r  requirements.txt

npm ci --dev

./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

/opt/star-burger/venv/bin/python3 /opt/star-burger/manage.py migrate

systemctl restart star-burger2

if [ -v $RB_TOKEN ]; then
  rev=$(git rev-parse --short HEAD)
  curl    -H "X-Rollbar-Access-Token: $RB_TOKEN" \
          -H "Content-Type: application/json" \
          -X  POST \
          -d  '{"environment": "production", "revision":"'${rev}'", "rollbar_name": "Alex", "local_username": "Alex", "comment": "deployment", "status": "succeeded"}'\
          https://api.rollbar.com/api/1/deploy
  else
    echo "Токен Rollbar не задан. Уведомление о деплое не будет направлено"
fi

echo "Код обновлен, юнит 'star-burger2.service' перезапущен"

