#!/bin/bash

set -e

cd /opt/star-burger
git  pull

rev=$(git rev-parse --short HEAD)

curl    -H "X-Rollbar-Access-Token: 948459ff5a2b490f86cfee685d15b037" \
        -H "Content-Type: application/json" \
        -X  POST \
        -d  '{"environment": "production", "revision":"'${rev}'", "rollbar_name": "Alex", "local_username": "Alex", "comment": "deployment", "status": "succeeded"}'\
        https://api.rollbar.com/api/1/deploy

/opt/star-burger/venv/bin/pip install -r  requirements.txt

npm ci --dev

./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"

/opt/star-burger/venv/bin/python3 /opt/star-burger/manage.py migrate

systemctl restart star-burger2

echo "Код обновлен, сервис star-burger2.service перезапущен"
