# Generated by Django 3.2.15 on 2023-06-08 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230608_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Не обработан'), ('COOK', 'Готовится'), ('DLVR', 'Доставка'), ('DONE', 'Доставлен')], default='NEW', max_length=4, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
