# Generated by Django 3.2.15 on 2023-06-08 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_called',
            field=models.DateTimeField(null=True, verbose_name='Созвон с клиентом'),
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_delivered',
            field=models.DateTimeField(null=True, verbose_name='Доставлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_registered',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Зарегестрирован'),
        ),
    ]
