# Generated by Django 3.2.15 on 2023-06-08 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20230608_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CSH', 'Наличными'), ('CRD', 'Картой')], db_index=True, default='CSH', max_length=4, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_called',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Созвон с клиентом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_delivered',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_registered',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Зарегестрирован'),
        ),
    ]
