# Generated by Django 3.2.15 on 2023-06-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('01', 'Не обработан'), ('02', 'Готовится'), ('03', 'Доставка'), ('04', 'Доставлен')], db_index=True, default='01', max_length=4, verbose_name='Статус'),
        ),
    ]
